on: 
  push:
    branches:
      - publish-test

jobs:
  publish-components:
    name: Publish Components to registry
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install pd
        env:
          PD_API_KEY: ${{ secrets.PD_API_KEY }}
        run: |
          curl -O https://cli.pipedream.com/linux/amd64/latest/pd.zip
          unzip pd.zip
          pwd
          ls -lh
          mkdir -p $HOME/.config/pipedream
          echo "api_key = $PD_API_KEY" > $HOME/.config/pipedream/config
          #./pd list components
      - name: get changed files
        id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'
      - run: |
          #curl -O https://cli.pipedream.com/linux/amd64/latest/pd.zip
          # unzip pd.zip
          pwd
          ls -lh
          ./pd list components
          mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
          for added_modified_file in "${added_modified_files[@]}"; do
            # starts with components, ends with .js and not app.js
            if [[ $added_modified_file == components/* ]] && [[ $added_modified_file == *.js ]] && [[ $added_modified_file != *.app.js ]]
            then
              echo "${added_modified_file} will be added to the registry"
              cat $added_modified_file
            else
              echo "${added_modified_file} will not be added to the registry"
              cat $added_modified_file
            fi
          done
      - name: remove config
        run: |
          rm $HOME/.config/pipedream
