name: Pull Request Checks

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

on:
  pull_request:
    branches:
      - master

jobs:

  spellcheck-markdown-files:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jitterbit/get-changed-files@v1
      id: changed_files
    - id: md_changed_files
      outputs:
        files:
          description: The files to check for spelling mistakes
      run: |-
        files=''
        for f in ${{ steps.changed_files.outputs.all }}
        do
          ext="${f##*.}"
          if [ $ext = "md" ]
          then
            files="${f} ${files}"
          fi
        done

        echo "::set-output name=files::${files}"
    - uses: rojopolis/spellcheck-github-actions@0.14.0
      name: Spellcheck
      if: ${{ steps.md_changed_files.outputs.files }}
      with:
        source_files: ${{ steps.md_changed_files.outputs.files }}
        task_name: Markdown

  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files
          # within `super-linter`
          fetch-depth: 0

      - name: Setup Node Env
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install Dependencies
        run: npm ci

      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc
          LINTER_RULES_PATH: /
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_JSON: true
